;Features
;    "COM_ROT"                                                                      ;#==> return enumeration of the running object table and pointer to the table in memory.
;    "COM_Get Excel.Application"                                                    ;#==> return pointer to existing object
;    "COM_New Excel.Application"                                                    ;#==> return pointer to new object
;    "COM_Exec <ptr> Application.ActiveWorkbook.ActiveWorksheet.UsedRange.value"    ;#==> return properties
;    "COM_Exec <ptr> Application.ActiveWorkbook.ActiveWorksheet.UsedRange"
