;Features
;    "COM_ROT"                                                                      ;#==> return enumeration of the running object table and pointer to the table in memory.
;    "COM_Get Excel.Application"                                                    ;#==> return pointer to existing object
;    "COM_New Excel.Application"                                                    ;#==> return pointer to new object
;    "COM_P_Get <obj> <key>"                                                        ;#==> return pointer to property
;    "COM_P_Set <obj> <key> <value>"                                                ;#==> return true or false, depending on whether the property is read only or not.
;    "COM_P_Val <ptr>"                                                              ;#==> return value of property
;    "COM_M_Exe <ptr> <key> <value>"
